config/routes.rb
Rails.application.routes.draw do

  devise_for :users,	path_names: {sign_in: "login", sign_out: "logout"},
  										controllers: {omniauth_callbacks: "omniauth_callbacks"}
  get '/secret', to: 'pages#secret', as: :secret
  root to: 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :zxcvbnable#, :confirmable, :lockable

 	# def send_devise_notification(notification, *args)
	#   devise_mailer.send(notification, self, *args).deliver_later
	# end

	validates_presence_of :username
	validates_uniqueness_of :username

	def self.from_omniauth(auth)	  
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.provider = auth.provider 
	    user.uid = auth.uid
	    user.username = auth.info.nickname
	  end
	end

	def self.new_with_session(params, session)
		if session["devise.user_attributes"]
			new(session["devise.user_attributes"], without_protection: true) do |user|
				user.attributes = params
				user.valid?
			end
		else
			super
		end
	end

	def password_required?
		super && provider.blank?
	end

	def update_with_password(params, *options)
		if encrypted_password.blank?
			update_attributes(params, *options)
		else
			super
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :username
	  devise_parameter_sanitizer.for(:account_update) << :username
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def all
		user = User.from_omniauth(request.env["omniauth.auth"])
		if user.persisted?
			flash[:notice] = "Signed In!"
			sign_in_and_redirect user
		else
			session["devise.user_attributes"] = user.attributes
			redirect_to new_user_registration_url
		end
	end

	alias_method :twitter,	:all
	alias_method :facebook,	:all

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: [:secret]
end

app/helpers/application_helper.rb
module ApplicationHelper
	def header(text)
	  content_for(:header) { text.to_s }
	end
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse">
	  <div class="container">
	    <div class="navbar-header">
	      <%= link_to 'Devise Demo', root_path, class: 'navbar-brand' %>
	    </div>
	    <div id="navbar">
	      <ul class="nav navbar-nav">
	        <li><%= link_to 'Home', root_path %></li>
	        <% if user_signed_in? %>
				    <li><%= link_to 'Secret', secret_path %></li>
				  <% end %>
	      </ul>
	      <ul class="nav navbar-nav pull-right">
	        <% if user_signed_in? %>
	          <li class="dropdown">
	            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	              <%= current_user.username %>
	              <span class="caret"></span>
	            </a>
	            <ul class="dropdown-menu" role="menu">
	              <li><%= link_to 'Profile', edit_user_registration_path %></li>
	              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
	            </ul>
	          </li>
	        <% else %>
	        	<li class="dropdown">
	        		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	        			Log In
	        			<span class="caret"></span>
	        		</a>
		        	<ul class="dropdown-menu" role="menu">
			          <li><%= link_to 'Log In', new_user_session_path %></li>
			          <li><%= link_to 'Log In with Twitter', user_omniauth_authorize_path(:twitter) %></li>
			          <li><%= link_to 'Log In with Facebook', user_omniauth_authorize_path(:facebook) %></li>
			          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
			         </ul>
	        	</li>
	        <% end %>
	      </ul>
	    </div>
	  </div>
	</nav>
	<div class="container">
	  <% flash.each do |key, value| %>
	    <div class="alert alert-<%= key %>">
	      <%= value %>
	    </div>
	  <% end %>
	</div>
	<%= yield :top_content %>
	<div class="container">
	    <h1><%= yield :header %></h1>
	  <%= yield %>
	</div>
</body>
</html>

app/views/pages/index.html.erb
<% if current_user.blank? %>
	<% content_for :top_content do %>
	  <div class="jumbotron">
	    <div class="container">
	      <h1>Welcome!</h1>
	      <p>Register to get started.</p>
	      <p>
	        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
	      </p>
	    </div>
	  </div>
	<% end %>
<% else %>
	<%= "Hi " + "#{current_user.username}" %>
<% end %>

app/views/pages/secret.html.erb
<% header "Secret!" %>